export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_CART_ITEM = "DELETE_CART_ITEM"

export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS"
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS"
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS"
export const POST_BOOK_SUCCESS = "POST_BOOK_SUCCESS"
